### ISSUE TITLE
Serverless implementation

### ISSUE THREAD

**Issue by LesterCovax** [jdistler/xrb_reddit_tipbot#2]
Since it's python based, it may be worth looking into using something like AWS Lambda.  I'm sure that the footprint is already quite low but it may be a good use case.

**Comment by jdistler** [comment]
Currently the application is deployed to an EC2 instance on AWS. It's on a free-tier T1 Micro instance and doesn't look like it will ever run out of credits. I'll keep this idea on the back burner while I work on pushing out additional features for the bot. It would be nice to not have to maintain deployments through Lambda.

**Comment by jdistler** [comment]
I'm going to close this issue for now and revisit this idea at a later date. I've moved away from using AWS as my cloud provider due to high fees.
